version: '3.9'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus-storage:/var/lib/influxdb2:rw
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --storage.tsdb.retention.time=1y
    ports:
      - ${DOCKER_PROMETHEUS_INIT_PORT}:9090
    restart: unless-stopped
    environment:
      TZ: "Europe/Kiev"
    networks:
      - monitor-net
  influxdb:
    image: influxdb:2.1.1
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: [ "./entrypoint.sh" ]
    restart: on-failure
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086
    networks:
      - monitor-net
  grafana:
    image: grafana/grafana
    user: root
    depends_on:
      - prometheus
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    hostname: grafana
    restart: unless-stopped
    environment:
      TZ: "Europe/Kiev"
    networks:
      - monitor-net

volumes:
  grafana-storage:
  influxdb-storage:
  prometheus-storage:

networks:
  monitor-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
